"""add automation_id to test_case

Revision ID: d04cd83a87fd
Revises: b5c6d7e8f9a0
Create Date: 2026-04-16 07:17:02.623137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04cd83a87fd'
down_revision: Union[str, None] = 'b5c6d7e8f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('automation_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_test_cases_automation_id'), 'test_cases', ['automation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_automation_id'), table_name='test_cases')
    op.drop_column('test_cases', 'automation_id')
    # ### end Alembic commands ###
